uploads = []

[[generated]]
id = "pjKoj_BtG9B2cwmbB-cy1"
uri = "file://uploads/category-bakery.png"
type = "image"
title = "generated_image"

[[generated]]
id = "cjEZcqGtd2NaLDMOd1P7X"
uri = "file://server/public/uploads/banners/banner-1.png"
type = "image"
title = "generated_image"

[[generated]]
id = "VPw1EJ7YOqcavtV_nzEo6"
uri = "file://server/public/uploads/banners/banner-2.png"
type = "image"
title = "generated_image"

[[generated]]
id = "xavJmY3pDv2aPbZwAAV5x"
uri = "file://server/public/uploads/banners/banner-3.png"
type = "image"
title = "generated_image"

[[generated]]
id = "vTKDiQm30VmxQqvOrE2LL"
uri = "file://server/public/uploads/banners/banner-4.png"
type = "image"
title = "generated_image"

[[generated]]
id = "t9vVyhkGIUUrdzRJCvbBW"
uri = "file://server/public/uploads/banners/banner-5.png"
type = "image"
title = "generated_image"

[[generated]]
id = "7uwS6v5kq3MaVlDCjr6zm"
uri = "file://attached_assets/generated_images/generated_image.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "aaowI2qXopw_0ixkf8Qdq"
uri = "file://uploads/category-bakery.png"
type = "image"
title = "صورة قسم المخبوزات"
