// Website CMS validation (audit finding H-17).
//
// PUT /api/admin/website-cms/:section wrote `{ ...req.body, updatedAt }` straight
// into websiteContent/{section} — no schema, no allowlist, no size limits — and that
// document is served verbatim by the PUBLIC GET /api/website-content.
//
// The two image routes had the same shape of problem from the other direction: they
// wrote `{ [field]: url }` where `field` came from the request body, so any key at
// all could be created or overwritten in a public document.
//
// WHERE THE CONTENT IS RENDERED — checked before deciding how to validate:
//   • client/screens/WebsiteCmsTab.tsx (the admin editor) puts every value into a
//     React Native <TextInput>/<ThemedText>. React Native has no innerHTML, so
//     nothing here can execute.
//   • server/templates/landing-public.html and landing-page.html do NOT read the CMS.
//   • server/templates/admin.html renders screenshot URLs through its own escHtml().
//
// So Stored XSS is not reachable through any renderer in THIS repository today. The
// endpoint exists to feed an external marketing site (Arabic copy, SEO/OG tags,
// store links) whose renderer we do not control — which is exactly why raw markup
// must not be storable here. The finding is real on the write side; the "→ rendered
// as HTML" leg is out of tree, and that is the argument for rejecting markup at the
// door rather than hoping the consumer escapes it.
//
// FIELD NATURE — no field in any section is meant to carry HTML. Both admin UIs
// expose plain single-line/multiline text inputs, URL inputs and switches. So:
//   • text fields reject tag-like input outright (400) rather than being silently
//     stripped or escaped: an admin typing markup has made a mistake and should be
//     told, and a stripped value would silently lose their content;
//   • URL fields must be http(s), which is what makes `javascript:` unrepresentable
//     even though those values end up in href/src on the marketing site.
import { z } from "zod";

/** The sections that exist in websiteContent. Mirrors CMS_SECTIONS in routes.ts. */
export const CMS_SECTIONS = [
  "hero", "features", "stats", "faq",
  "downloadLinks", "screenshots", "contact", "seo", "footer",
] as const;
export type CmsSection = (typeof CMS_SECTIONS)[number];

/**
 * Opens a tag, a closing tag, a comment or a processing instruction.
 * A bare "<" used as a less-than sign is deliberately still allowed.
 */
const TAG_LIKE = /<\s*\/?\s*[a-zA-Z!?]/;
/** Schemes that only ever appear in payloads, never in marketing copy. */
const DANGEROUS_SCHEME = /(javascript|vbscript)\s*:|data\s*:\s*text\/html/i;

/** A plain-text CMS field: bounded, trimmed, and free of markup. */
const plainText = (max: number) =>
  z
    .string()
    .max(max, `الحد الأقصى ${max} حرفاً`)
    .transform((s) => s.trim())
    .refine((s) => !TAG_LIKE.test(s), "لا يُسمح بوسوم HTML في هذا الحقل")
    .refine((s) => !DANGEROUS_SCHEME.test(s), "رابط غير مسموح");

/**
 * A URL field. Empty string is allowed — that is how both admin UIs clear a value —
 * but anything non-empty must be an absolute http(s) URL, which is what keeps
 * `javascript:` out of the href/src it eventually becomes.
 */
const httpUrl = (max = 2000) =>
  z
    .string()
    .max(max, `الحد الأقصى ${max} حرفاً`)
    .transform((s) => s.trim())
    .refine(
      (s) => s === "" || /^https?:\/\/[^\s<>"']+$/i.test(s),
      "يجب أن يكون رابطاً يبدأ بـ http:// أو https://",
    );

/** A stable list-item id generated by the admin UI. */
const itemId = z.string().max(64).regex(/^[A-Za-z0-9_-]+$/, "معرّف غير صالح");
const orderNum = z.number().int().min(0).max(999);

// ── Per-section schemas ─────────────────────────────────────────────────────
//
// Every field is optional because BOTH admin UIs save partial payloads and the route
// writes with { merge: true } — admin.html's hero form, for example, sends four
// fields and never touches heroImageUrl. `.strict()` is what turns this into an
// allowlist: any key that is not named here fails the parse.

const heroSchema = z
  .object({
    title_ar: plainText(120),
    subtitle_ar: plainText(300),
    ctaPrimary_ar: plainText(40),
    ctaSecondary_ar: plainText(40),
    heroImageUrl: httpUrl(),
  })
  .partial()
  .strict();

const featuresSchema = z
  .object({
    items: z
      .array(
        z
          .object({
            id: itemId,
            icon: plainText(40),
            title_ar: plainText(80),
            desc_ar: plainText(300),
            order: orderNum,
          })
          .partial({ icon: true, title_ar: true, desc_ar: true, order: true })
          .strict(),
      )
      .max(12, "الحد الأقصى 12 عنصراً"),
  })
  .partial()
  .strict();

const statsSchema = z
  .object({
    // Display strings, not numbers — the UI placeholders are "50,000+" and "4.8".
    downloads: plainText(32),
    vendors: plainText(32),
    cities: plainText(32),
    rating: plainText(32),
  })
  .partial()
  .strict();

const faqSchema = z
  .object({
    items: z
      .array(
        z
          .object({
            id: itemId,
            question_ar: plainText(200),
            answer_ar: plainText(1000),
            order: orderNum,
          })
          .partial({ question_ar: true, answer_ar: true, order: true })
          .strict(),
      )
      .max(30, "الحد الأقصى 30 سؤالاً"),
  })
  .partial()
  .strict();

const downloadLinksSchema = z
  .object({
    appStoreUrl: httpUrl(),
    playStoreUrl: httpUrl(),
    appStoreEnabled: z.boolean(),
    playStoreEnabled: z.boolean(),
  })
  .partial()
  .strict();

const screenshotsSchema = z
  .object({
    images: z.array(httpUrl()).max(12, "الحد الأقصى 12 صورة"),
  })
  .partial()
  .strict();

const contactSchema = z
  .object({
    email: z.string().max(254).transform((s) => s.trim())
      .refine((s) => s === "" || z.string().email().safeParse(s).success, "بريد إلكتروني غير صالح"),
    phone: plainText(32),
    whatsapp: plainText(32),
    // Social fields accept either a handle or a full URL, so they are plain text with
    // the markup guard rather than strict URLs.
    instagram: plainText(200),
    twitter: plainText(200),
    facebook: plainText(200),
    address_ar: plainText(300),
  })
  .partial()
  .strict();

const seoSchema = z
  .object({
    title_ar: plainText(120),
    description_ar: plainText(320),
    keywords: plainText(400),
    ogImageUrl: httpUrl(),
  })
  .partial()
  .strict();

// admin.html has a footer form (tagline_ar / tagline_en); the React Native tab does not.
const footerSchema = z
  .object({
    tagline_ar: plainText(200),
    tagline_en: plainText(200),
  })
  .partial()
  .strict();

export const WEBSITE_CONTENT_SCHEMAS: Record<CmsSection, z.ZodTypeAny> = {
  hero: heroSchema,
  features: featuresSchema,
  stats: statsSchema,
  faq: faqSchema,
  downloadLinks: downloadLinksSchema,
  screenshots: screenshotsSchema,
  contact: contactSchema,
  seo: seoSchema,
  footer: footerSchema,
};

/**
 * The image fields each section may have written by the upload/delete routes.
 * `field` used to come straight from the request body, so ANY key — including one
 * that overwrites text content with an image URL — could be created.
 */
export const CMS_IMAGE_FIELDS: Record<CmsSection, readonly string[]> = {
  hero: ["heroImageUrl"],
  seo: ["ogImageUrl"],
  screenshots: [],
  features: [],
  stats: [],
  faq: [],
  downloadLinks: [],
  contact: [],
  footer: [],
};

/**
 * Sentinels both admin UIs send when an upload/delete must NOT write a field:
 * screenshots keeps its URLs in the `images` array, saved by a separate PUT.
 * They are accepted so the existing flow keeps working, and simply skip the write —
 * previously `__array__` was written into the document as a junk key.
 */
export const CMS_IMAGE_NO_PERSIST = ["temp", "__array__"] as const;

export function isCmsSection(value: unknown): value is CmsSection {
  return typeof value === "string" && (CMS_SECTIONS as readonly string[]).includes(value);
}

/**
 * Parse an admin CMS payload for one section.
 *
 * Returns the validated, trimmed data — never the caller's object — or the list of
 * offending field paths. Only paths are returned: they are the admin's own form
 * field names, which the UI needs, and they carry no internal detail.
 */
export function parseWebsiteContent(
  section: CmsSection,
  body: unknown,
): { ok: true; data: Record<string, unknown> } | { ok: false; fields: string[] } {
  // A JSON body that is not an object at all (array, string, null) must not reach
  // Firestore's set().
  if (body === null || typeof body !== "object" || Array.isArray(body)) {
    return { ok: false, fields: ["_root"] };
  }
  const result = WEBSITE_CONTENT_SCHEMAS[section].safeParse(body);
  if (!result.success) {
    const fields = result.error.issues
      .map((i) => (i.path.length ? i.path.join(".") : "_root"))
      .slice(0, 10);
    return { ok: false, fields: [...new Set(fields)] };
  }
  return { ok: true, data: result.data as Record<string, unknown> };
}
